'use client'
import {useEffect,useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {Users,Shuffle,Mic2,ChevronLeft,Camera,Check} from 'lucide-react'
import {createClient} from '@/lib/supabase/client'
import {friendlyError} from '@/lib/utils'
import {BrandLogo} from '@/components/brand-logo'
type Country={id:string;name_ar:string};type City={id:string;country_id:string;name_ar:string};type Interest={id:string;name_ar:string}
const moods=['😊 مبسوط','😌 هادئ','🤔 بفكر','🔥 متحمس','☕ رايق','💬 عايز أتكلم']
export default function Onboarding(){
 const s=useMemo(()=>createClient(),[]),r=useRouter()
 const [screen,setScreen]=useState(0),[step,setStep]=useState(1),[countries,setCountries]=useState<Country[]>([]),[cities,setCities]=useState<City[]>([]),[interests,setInterests]=useState<Interest[]>([])
 const [name,setName]=useState(''),[birth,setBirth]=useState(''),[gender,setGender]=useState(''),[country,setCountry]=useState(''),[city,setCity]=useState(''),[bio,setBio]=useState(''),[mood,setMood]=useState('☕ رايق'),[selected,setSelected]=useState<string[]>([]),[avatar,setAvatar]=useState<File|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{(async()=>{const [{data:c},{data:ct},{data:i}]=await Promise.all([s.from('countries').select('id,name_ar').order('name_ar'),s.from('cities').select('id,country_id,name_ar').order('name_ar'),s.from('interests').select('id,name_ar').order('name_ar')]);setCountries(c||[]);setCities(ct||[]);setInterests(i||[])})()},[s])
 const available=cities.filter(x=>x.country_id===country)
 async function save(){setBusy(true);setMsg('');const {data:{user}}=await s.auth.getUser();if(!user){r.push('/login');return}const {error}=await s.rpc('complete_profile',{p_display_name:name,p_birth_date:birth,p_country_id:country,p_city_id:city,p_bio:bio||null,p_mood:mood,p_interest_ids:selected,p_gender:gender});if(error){setMsg(friendlyError(error.message));setBusy(false);return}if(avatar){const ext=avatar.name.split('.').pop()?.toLowerCase()||'jpg',path=`${user.id}/${crypto.randomUUID()}.${ext}`;const up=await s.storage.from('avatars').upload(path,avatar,{upsert:false,contentType:avatar.type});if(!up.error){const {data}=s.storage.from('avatars').getPublicUrl(path);await s.from('profiles').update({avatar_url:data.publicUrl}).eq('id',user.id)}}r.push('/home');r.refresh()}
 if(screen===0)return <main className="mx-auto min-h-[100dvh] max-w-md overflow-hidden px-5 pb-6 pt-8"><div className="relative text-center"><div className="mx-auto grid max-w-[330px] grid-cols-3 items-center gap-2"><div className="grid h-24 w-24 place-items-center rounded-full border-4 border-white bg-gradient-to-br from-[#C7F8FF] to-[#9ABEFF] shadow-lg"><Users size={39} className="text-[#0E69F4]"/></div><BrandLogo size={118}/><div className="grid h-24 w-24 place-items-center rounded-full border-4 border-white bg-gradient-to-br from-[#F6C6FF] to-[#BFA8FF] shadow-lg"><Mic2 size={39} className="text-[#6D2AE8]"/></div></div><h1 className="mt-5 text-[48px] font-black leading-none">لمتنا</h1><h2 className="mt-7 text-[30px] font-black">مكانك للتعارف واللمة الصوتية</h2><p className="mx-auto mt-3 max-w-[340px] text-[17px] font-bold leading-8 text-[#67748E]">اكتشف أصدقاء جدد من جميع أنحاء العالم العربي عبر الدردشة العشوائية واللَمّات الصوتية.</p></div><div className="mt-7 space-y-3">{[[Users,'اكتشف أصدقاء جدد','تعرف على أشخاص يشاركونك الاهتمامات'],[Shuffle,'دردشة عشوائية','ابدأ محادثات ممتعة وتعرف على ناس جدد'],[Mic2,'انضم إلى اللَمّة الصوتية','تواصل بصوتك وشارك في لَمّات حقيقية']].map(([I,t,d]:any)=><div key={t} className="mobile-card flex items-center gap-4 rounded-[24px] p-4"><span className="grid h-12 w-12 place-items-center rounded-[18px] bg-gradient-to-br from-[#E7F9FF] to-[#F2E9FF]"><I className="text-[#1369F5]"/></span><div className="flex-1 text-right"><p className="font-black">{t}</p><p className="mt-1 text-xs font-bold text-[#73809A]">{d}</p></div><ChevronLeft className="text-[#1166F5]"/></div>)}</div><button onClick={()=>setScreen(1)} className="lammetna-gradient mt-7 flex h-16 w-full items-center justify-between rounded-[24px] px-5 text-2xl font-black text-white hero-shadow"><span>ابدأ الآن</span><span className="grid h-10 w-10 place-items-center rounded-[15px] bg-white/20"><ChevronLeft/></span></button></main>
 return <main className="mx-auto min-h-[100dvh] max-w-md p-5"><div className="flex items-center gap-3"><BrandLogo size={52}/><div><p className="text-xs font-black text-[#1268F5]">استكمال الملف</p><h1 className="text-2xl font-black">عرّفنا بنفسك</h1></div></div><div className="mt-5 flex gap-2">{[1,2,3,4].map(n=><span key={n} className={`h-2 flex-1 rounded-full ${n<=step?'lammetna-gradient':'bg-[#DDE7F2]'}`}/>)}</div><section className="mobile-card mt-5 rounded-[30px] p-5">
  {step===1?<div className="space-y-4"><h2 className="text-xl font-black">المعلومات الأساسية</h2><label className="block text-sm font-black">الاسم الظاهر<input className="mt-2 h-12 w-full rounded-2xl bg-[#F3F7FC] px-4 outline-none" value={name} onChange={e=>setName(e.target.value)} placeholder="اكتب اسمك"/></label><label className="block text-sm font-black">تاريخ الميلاد<input type="date" className="mt-2 h-12 w-full rounded-2xl bg-[#F3F7FC] px-4 outline-none" value={birth} onChange={e=>setBirth(e.target.value)}/></label><div><p className="mb-2 text-sm font-black">الجنس</p><div className="grid grid-cols-3 gap-2">{[['male','ذكر'],['female','أنثى'],['other','آخر']].map(([v,l])=><button key={v} onClick={()=>setGender(v)} className={`h-12 rounded-2xl font-black ${gender===v?'lammetna-gradient text-white':'bg-[#EEF4FA] text-[#36506F]'}`}>{l}</button>)}</div></div></div>:null}
  {step===2?<div className="space-y-4"><h2 className="text-xl font-black">مكانك</h2><select value={country} onChange={e=>{setCountry(e.target.value);setCity('')}} className="h-12 w-full rounded-2xl bg-[#F3F7FC] px-4 outline-none"><option value="">اختر الدولة</option>{countries.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select><select value={city} disabled={!country} onChange={e=>setCity(e.target.value)} className="h-12 w-full rounded-2xl bg-[#F3F7FC] px-4 outline-none"><option value="">اختر المدينة</option>{available.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></div>:null}
  {step===3?<div><h2 className="text-xl font-black">مزاجك واهتماماتك</h2><div className="mt-4 flex flex-wrap gap-2">{moods.map(m=><button key={m} onClick={()=>setMood(m)} className={`rounded-full px-3 py-2 text-xs font-black ${mood===m?'lammetna-gradient text-white':'bg-[#EEF4FA] text-[#36506F]'}`}>{m}</button>)}</div><div className="mt-5 flex flex-wrap gap-2">{interests.map(x=>{const on=selected.includes(x.id);return <button key={x.id} onClick={()=>setSelected(v=>on?v.filter(y=>y!==x.id):[...v,x.id])} className={`rounded-full px-3 py-2 text-xs font-black ${on?'bg-[#6C48FF] text-white':'bg-[#F1F5FA] text-[#4B5D78]'}`}>{x.name_ar}</button>})}</div></div>:null}
  {step===4?<div className="space-y-4"><h2 className="text-xl font-black">اللمسات الأخيرة</h2><label className="flex h-24 cursor-pointer items-center justify-center gap-3 rounded-[24px] border-2 border-dashed border-[#B8CFF0] bg-[#F5FAFF] text-[#1567F4]"><Camera/> اختر صورة شخصية<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setAvatar(e.target.files?.[0]||null)}/></label><textarea value={bio} maxLength={500} onChange={e=>setBio(e.target.value)} placeholder="نبذة قصيرة عنك" className="min-h-28 w-full rounded-[22px] bg-[#F3F7FC] p-4 outline-none"/></div>:null}
  {msg?<p className="mt-4 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{msg}</p>:null}
  <div className="mt-6 flex gap-2">{step>1?<button onClick={()=>setStep(step-1)} className="h-13 flex-1 rounded-2xl bg-[#EEF3F9] py-3 font-black">السابق</button>:null}<button onClick={()=>step<4?setStep(step+1):save()} disabled={busy||(step===1&&(!name||!birth||!gender))||(step===2&&(!country||!city))} className="lammetna-gradient flex-1 rounded-2xl py-3 font-black text-white">{step<4?'التالي':busy?'جاري الحفظ...':'حفظ ومتابعة'}</button></div>
 </section></main>
}
