'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {AppShell} from '@/components/app-shell'
import {PageHeader} from '@/components/page-header'
import {Button} from '@/components/ui/button'
import {Card,CardContent} from '@/components/ui/card'
import {Input} from '@/components/ui/input'
import {Eye,Gift,MessageCircle,Sparkles,Star,UserRound} from 'lucide-react'

export default function SocialHub(){
 const s=useMemo(()=>createClient(),[]),[uid,setUid]=useState(''),[visitors,setVisitors]=useState<any[]>([]),[count,setCount]=useState(0),[q,setQ]=useState<any>(null),[answer,setAnswer]=useState(''),[missions,setMissions]=useState<any[]>([]),[prompts,setPrompts]=useState<any[]>([]),[status,setStatus]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);const {data:{user}}=await s.auth.getUser();if(!user){setBusy(false);return}setUid(user.id);const today=new Date().toISOString().slice(0,10);const [v,c,dq,da,md,mc,pp]=await Promise.all([s.rpc('get_my_profile_visitors',{p_limit:20}),s.rpc('my_profile_visitor_count'),s.from('daily_questions').select('id,question_ar').eq('active',true).eq('active_date',today).maybeSingle(),s.from('daily_answers').select('question_id,answer,highlighted_until').eq('user_id',user.id),s.from('daily_mission_definitions').select('code,title_ar,description_ar,reward_stars').eq('active',true),s.from('daily_mission_claims').select('mission_code,reward_stars').eq('user_id',user.id).eq('claim_date',today),s.from('profile_prompts').select('id,prompt_key,answer,sort_order').eq('user_id',user.id).order('sort_order')]);setVisitors(v.data||[]);setCount(Number(c.data||0));setQ(dq.data||null);const old=(da.data||[]).find((x:any)=>x.question_id===dq.data?.id);setAnswer(old?.answer||'');setMissions((md.data||[]).map((x:any)=>({...x,claimed:(mc.data||[]).some((y:any)=>y.mission_code===x.code)})));setPrompts(pp.data||[]);setBusy(false)}
 useEffect(()=>{load()},[])
 function msg(e:any,ok:string){setNotice(e?((e.message||'').includes('insufficient_stars')?'رصيد النجوم غير كافٍ.':'تعذر التنفيذ الآن.'):ok)}
 async function saveAnswer(){if(!q||!answer.trim())return;setBusy(true);const {error}=await s.rpc('answer_daily_question',{p_question:q.id,p_answer:answer.trim()});msg(error,'تم حفظ إجابتك اليومية.');setBusy(false)}
 async function highlight(){if(!q)return;setBusy(true);const {error}=await s.rpc('highlight_my_daily_answer',{p_question:q.id});msg(error,'تم إبراز إجابتك ✨');setBusy(false)}
 async function unlock(){setBusy(true);const {error}=await s.rpc('unlock_profile_visitors_24h');msg(error,'تم فتح هويات الزوار لمدة 24 ساعة.');await load()}
 async function claim(code:string){setBusy(true);const {data,error}=await s.rpc('claim_daily_mission',{p_code:code});msg(error,error?'':('تم استلام '+Number(data||0)+' نجمة ⭐'));await load()}
 async function savePrompt(key:string,value:string,order:number){if(!value.trim())return;setBusy(true);const {error}=await s.rpc('set_profile_prompt',{p_prompt_key:key,p_answer:value.trim(),p_sort_order:order});msg(error,'تم حفظ الإجابة.');await load()}
 async function setSocial(){if(!status.trim())return;setBusy(true);const {error}=await s.rpc('set_social_status',{p_status:status.trim(),p_hours:24});msg(error,'تم نشر حالتك لمدة 24 ساعة.');setBusy(false)}
 return <AppShell><PageHeader title="مساحتي"/><main className="space-y-4 p-4">{notice&&<p className="rounded-2xl bg-[#EAF2FC] p-3 text-sm font-bold text-[#1560BD]">{notice}</p>}
 <Card><CardContent><div className="flex items-center gap-2"><Eye className="text-[#1560BD]"/><div><h2 className="font-extrabold">مرّوا من هنا</h2><p className="text-xs text-slate-500">{count} زيارة مسجلة</p></div></div><div className="mt-3 space-y-2">{visitors.slice(0,6).map((x:any)=><div key={x.view_id} className="flex items-center gap-3 rounded-2xl bg-[#F4F8FD] p-3"><div className="grid h-10 w-10 place-items-center overflow-hidden rounded-full bg-[#EAF2FC] text-[#1560BD]">{x.identity_revealed&&x.avatar_url?<img src={x.avatar_url} className="h-full w-full object-cover" alt=""/>:<UserRound size={18}/>}</div><div className="flex-1"><p className="font-bold">{x.identity_revealed?(x.display_name||'مستخدم لمتنا'):'زائر مخفي'}</p><p className="text-xs text-slate-500">{x.identity_revealed?'الهوية متاحة':'يمكن فتح هوية الزوار لمدة 24 ساعة'}</p></div></div>)}</div><Button className="mt-3 w-full" variant="secondary" disabled={busy} onClick={unlock}>فتح هويات الزوار 24 ساعة · 20 ⭐</Button></CardContent></Card>
 <Card><CardContent><div className="flex items-center gap-2"><MessageCircle className="text-[#1560BD]"/><h2 className="font-extrabold">سؤال اليوم</h2></div>{q?<><p className="mt-3 font-bold">{q.question_ar}</p><Input className="mt-3" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="اكتب إجابتك..."/><div className="mt-2 grid grid-cols-2 gap-2"><Button onClick={saveAnswer} disabled={busy||!answer.trim()}>حفظ الإجابة</Button><Button variant="secondary" onClick={highlight} disabled={busy}>إبراز 24 ساعة · 10 ⭐</Button></div></>:<p className="mt-3 text-sm text-slate-500">لا يوجد سؤال مفعّل اليوم.</p>}</CardContent></Card>
 <Card><CardContent><div className="flex items-center gap-2"><Gift className="text-[#1560BD]"/><h2 className="font-extrabold">مهمات اليوم</h2></div><div className="mt-3 space-y-2">{missions.map((m:any)=><div key={m.code} className="rounded-2xl border border-[#DCE8F7] p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-bold">{m.title_ar}</p><p className="text-xs text-slate-500">{m.description_ar}</p></div><span className="whitespace-nowrap text-xs font-black text-amber-700">+{m.reward_stars} ⭐</span></div><Button className="mt-2 w-full" size="sm" variant={m.claimed?'outline':'secondary'} disabled={busy||m.claimed} onClick={()=>claim(m.code)}>{m.claimed?'تم الاستلام':'استلام المكافأة'}</Button></div>)}</div></CardContent></Card>
 <Card><CardContent><div className="flex items-center gap-2"><Sparkles className="text-[#1560BD]"/><h2 className="font-extrabold">عرّف الناس عليك</h2></div><Prompt label="حاجة ممكن نتكلم عنها بالساعات" k="talk_forever" n={0} existing={prompts} save={savePrompt}/><Prompt label="أكتر حاجة بتبسطني" k="makes_me_happy" n={1} existing={prompts} save={savePrompt}/><Prompt label="لو عندي يوم فاضي تمامًا" k="free_day" n={2} existing={prompts} save={savePrompt}/></CardContent></Card>
 <Card><CardContent><div className="flex items-center gap-2"><Star className="text-[#1560BD]"/><h2 className="font-extrabold">متواجد الآن</h2></div><p className="mt-2 text-xs text-slate-500">حالة اجتماعية مؤقتة لمدة 24 ساعة.</p><Input className="mt-3" value={status} onChange={e=>setStatus(e.target.value)} placeholder="مثال: فاضي لكوباية قهوة وكلام"/><Button className="mt-2 w-full" onClick={setSocial} disabled={busy||!status.trim()}>نشر الحالة</Button></CardContent></Card>
 </main></AppShell>
}
function Prompt({label,k,n,existing,save}:{label:string;k:string;n:number;existing:any[];save:(k:string,v:string,n:number)=>void}){const old=existing.find(x=>x.prompt_key===k)?.answer||'';const [v,setV]=useState(old);useEffect(()=>setV(old),[old]);return <div className="mt-3 rounded-2xl bg-[#F4F8FD] p-3"><p className="text-sm font-bold">{label}</p><Input className="mt-2 bg-white" value={v} onChange={e=>setV(e.target.value)} placeholder="إجابتك"/><Button className="mt-2" size="sm" variant="secondary" onClick={()=>save(k,v,n)}>حفظ</Button></div>}
