import Link from 'next/link'
import {redirect} from 'next/navigation'
import {Bell,Star,Plus,Users,Shuffle,Mic2,MessagesSquare,ChevronLeft,MapPin} from 'lucide-react'
import {createClient} from '@/lib/supabase/server'
import {AppShell} from '@/components/app-shell'
import {BrandLogo} from '@/components/brand-logo'
import {InterestButton} from '@/components/interest-button'
export default async function Home(){
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/login')
 const [{data:p},{data:w},{data:people},{count:requests}]=await Promise.all([s.from('profiles').select('id,display_name,profile_complete').eq('id',user.id).single(),s.from('star_wallets').select('balance').eq('user_id',user.id).single(),s.from('profiles').select('id,display_name,avatar_url,mood,cities(name_ar),birth_date,show_age').neq('id',user.id).eq('profile_complete',true).eq('discoverable',true).limit(8),s.from('connection_requests').select('*',{count:'exact',head:true}).eq('receiver_id',user.id).eq('status','pending')])
 if(!p?.profile_complete)redirect('/onboarding')
 const faces=(people||[]).slice(0,3)
 return <AppShell><main className="px-4 pb-6 pt-4">
  <header className="safe-top flex items-center justify-between"><div className="flex items-center gap-2"><BrandLogo size={48}/><div><h1 className="text-[28px] font-black">لمتنا</h1><p className="text-[11px] font-bold text-[#6B7891]">دائمًا مساحة أجمل مع أصدقاء جدد</p></div></div><div className="flex items-center gap-2"><Link href="/payments" className="flex h-11 items-center gap-2 rounded-full bg-white px-3 font-black shadow-sm ring-1 ring-[#E1EAF6]"><Star size={20} fill="#FFC21A" className="text-[#FFC21A]"/>{Number(w?.balance||0).toLocaleString('en-US')}</Link><Link href="/notifications" className="relative grid h-11 w-11 place-items-center rounded-full bg-white shadow-sm ring-1 ring-[#E1EAF6]"><Bell className="text-[#086AF4]" size={21}/>{requests?<span className="absolute right-1 top-1 h-2.5 w-2.5 rounded-full bg-[#FF1678] ring-2 ring-white"/>:null}</Link></div></header>
  <section className="lammetna-gradient hero-shadow relative mt-5 overflow-hidden rounded-[30px] p-5 text-white"><div className="absolute -left-10 -top-12 h-44 w-44 rounded-full bg-white/12 blur-2xl"/><div className="relative grid grid-cols-[1fr_140px] items-center gap-2"><div><h2 className="text-[28px] font-black leading-[1.25]">اكتشف عالماً<br/>من الأصدقاء الجدد</h2><p className="mt-2 text-sm font-bold leading-6 text-white/88">تواصل، دردش، وانضم إلى اللَمّات الصوتية مع أشخاص حقيقيين مثلك</p><Link href="/discover" className="mt-5 inline-flex items-center gap-2 rounded-[18px] bg-white px-4 py-3 text-sm font-black text-[#6427DC]">ابدأ الاستكشاف الآن <ChevronLeft size={18}/></Link></div><div className="relative h-40">{faces.map((x:any,i:number)=><div key={x.id} className={`absolute overflow-hidden rounded-full border-4 border-white shadow-lg ${i===0?'left-0 top-5 h-20 w-20':i===1?'right-0 top-0 h-20 w-20':'right-10 bottom-0 h-16 w-16'}`}>{x.avatar_url?<img src={x.avatar_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full w-full place-items-center bg-white/20 text-2xl font-black">{x.display_name?.[0]}</div>}</div>)}<span className="absolute bottom-0 left-1 grid h-14 w-14 place-items-center rounded-full border-2 border-white bg-[#149DF4]"><Plus size={28}/></span></div></div></section>
  <section className="mt-4 grid grid-cols-5 gap-2">{[[Users,'اكتشف','أصدقاء جدد','/discover'],[Shuffle,'دردشة عشوائية','أشخاص جدد الآن','/discover'],[Mic2,'اللَمّة','غرف صوتية','/spaces'],[Star,'رصيد النجوم','شحن ومميزات','/payments'],[MessagesSquare,'كلامنا','كل محادثاتك','/chats']].map(([I,t,d,h]:any)=><Link href={h} key={t} className="mobile-card rounded-[20px] px-2 py-3 text-center"><span className="mx-auto grid h-11 w-11 place-items-center rounded-[16px] bg-gradient-to-br from-[#E2F8FF] to-[#F3E7FF] text-[#1768F4]"><I size={22}/></span><p className="mt-2 text-[11px] font-black">{t}</p><p className="mt-1 text-[9px] font-bold leading-4 text-[#78849B]">{d}</p></Link>)}</section>
  <section className="mt-4 grid grid-cols-2 gap-3"><Link href="/chats" className="lammetna-gradient hero-shadow rounded-[26px] p-4 text-white"><div className="flex items-center gap-2"><MessagesSquare/><p className="text-2xl font-black">كلامنا</p></div><p className="mt-2 text-sm font-bold text-white/85">محادثاتك الخاصة في مكان واحد</p><span className="mt-4 inline-flex h-10 w-10 items-center justify-center rounded-full bg-white/20"><ChevronLeft/></span></Link><Link href="/payments" className="rounded-[26px] bg-gradient-to-br from-[#074A86] via-[#086DBB] to-[#5620CE] p-4 text-white shadow-lg"><p className="text-sm font-bold">رصيد النجوم</p><p className="mt-1 text-[28px] font-black">{Number(w?.balance||0).toLocaleString('en-US')}</p><p className="text-xs font-bold text-white/75">نجمة ⭐</p><span className="mt-4 inline-flex rounded-full bg-white px-3 py-2 text-xs font-black text-[#5722D5]">شراء نجوم +</span></Link></section>
  <section className="mt-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-[23px] font-black">وجوه جديدة ✨</h2><Link href="/discover" className="text-sm font-black text-[#1367F4]">عرض الكل</Link></div><div className="hide-scrollbar flex gap-3 overflow-x-auto pb-2">{(people||[]).map((x:any)=><div key={x.id} className="mobile-card min-w-[145px] overflow-hidden rounded-[22px]"><div className="relative h-36 bg-[#E8F2FB]">{x.avatar_url?<img src={x.avatar_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full w-full place-items-center text-4xl font-black text-[#1267F4]">{x.display_name?.[0]}</div>}<span className="absolute left-2 top-2 h-3 w-3 rounded-full bg-[#10D38B] ring-2 ring-white"/></div><div className="p-3"><p className="font-black">{x.display_name}</p><p className="mt-1 flex items-center gap-1 text-[11px] font-bold text-[#77839A]"><MapPin size={12}/>{x.cities?.name_ar||'مدينة غير محددة'}</p><div className="mt-2"><InterestButton userId={x.id}/></div></div></div>)}</div></section>
 </main></AppShell>
}
