'use client'
import {useEffect,useMemo,useState} from 'react'
import {Camera,Heart,MessageCircle,Share2,Flame,MapPin,UserRound,Eye,Gift,Sparkles,Star} from 'lucide-react'
import {createClient} from '@/lib/supabase/client'
import {AppShell} from '@/components/app-shell'
import {BrandLogo} from '@/components/brand-logo'
export default function SocialHub(){
 const s=useMemo(()=>createClient(),[]),[visitors,setVisitors]=useState<any[]>([]),[count,setCount]=useState(0),[q,setQ]=useState<any>(null),[answer,setAnswer]=useState(''),[missions,setMissions]=useState<any[]>([]),[prompts,setPrompts]=useState<any[]>([]),[status,setStatus]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);const {data:{user}}=await s.auth.getUser();if(!user){setBusy(false);return}const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const [v,c,dq,da,md,mc,pp]=await Promise.all([s.rpc('get_my_profile_visitors',{p_limit:20}),s.rpc('my_profile_visitor_count'),s.from('daily_questions').select('id,question_ar').eq('active',true).eq('active_date',today).maybeSingle(),s.from('daily_answers').select('question_id,answer,highlighted_until').eq('user_id',user.id),s.from('daily_mission_definitions').select('code,title_ar,description_ar,reward_stars').eq('active',true),s.from('daily_mission_claims').select('mission_code,reward_stars').eq('user_id',user.id).eq('claim_date',today),s.from('profile_prompts').select('id,prompt_key,answer,sort_order').eq('user_id',user.id).order('sort_order')]);setVisitors(v.data||[]);setCount(Number(c.data||0));setQ(dq.data||null);setAnswer((da.data||[]).find((x:any)=>x.question_id===dq.data?.id)?.answer||'');setMissions((md.data||[]).map((x:any)=>({...x,claimed:(mc.data||[]).some((y:any)=>y.mission_code===x.code)})));setPrompts(pp.data||[]);setBusy(false)}
 useEffect(()=>{load()},[])
 async function saveAnswer(){if(!q||!answer.trim())return;setBusy(true);const {error}=await s.rpc('answer_daily_question',{p_question:q.id,p_answer:answer.trim()});setNotice(error?'تعذر الحفظ.':'تم حفظ إجابتك اليومية.');setBusy(false)}
 async function claim(code:string){setBusy(true);const {data,error}=await s.rpc('claim_daily_mission',{p_code:code});setNotice(error?'تعذر التنفيذ.':`تم استلام ${Number(data||0)} نجمة ⭐`);await load()}
 async function social(){if(!status.trim())return;setBusy(true);const {error}=await s.rpc('set_social_status',{p_status:status.trim(),p_hours:24});setNotice(error?'تعذر النشر.':'تم نشر حالتك لمدة 24 ساعة.');setBusy(false)}
 return <AppShell><main className="px-4 pb-5 pt-4"><header className="safe-top flex items-center justify-between"><div className="flex items-center gap-3"><BrandLogo size={54}/><div><h1 className="text-[32px] font-black">سوالف</h1><p className="text-sm font-bold text-[#6E7A92]">شارك لحظاتك وسوالفك مع الأصدقاء</p></div></div><button className="lammetna-gradient grid h-12 w-12 place-items-center rounded-[18px] text-white shadow-lg"><Camera/></button></header>
 <section className="mobile-card mt-4 rounded-[24px] p-4"><div className="flex items-center justify-between"><h2 className="font-black">🔥 المواضيع الرائجة</h2><span className="text-xs font-black text-[#703DEB]">عرض الكل</span></div><div className="hide-scrollbar mt-3 flex gap-2 overflow-x-auto">{['💗 حب','✨ جمال','✈️ سفر','☕ قهوة','👥 تعارف','# تقنية'].map(x=><span key={x} className="whitespace-nowrap rounded-[14px] bg-gradient-to-br from-[#FFF0F8] to-[#EEF5FF] px-3 py-2 text-xs font-black">{x}</span>)}</div></section>
 {notice?<p className="mt-3 rounded-2xl bg-[#EDF5FF] p-3 text-sm font-bold text-[#2B5288]">{notice}</p>:null}
 <FeedCard title="سؤال اليوم" subtitle={q?.question_ar||'شاركنا يومك'} icon="☕"><textarea value={answer} onChange={e=>setAnswer(e.target.value)} className="min-h-24 w-full rounded-[20px] bg-[#F3F7FB] p-3 text-sm outline-none" placeholder="اكتب إجابتك..."/><button onClick={saveAnswer} disabled={busy||!answer.trim()} className="lammetna-gradient mt-3 rounded-2xl px-4 py-2 text-sm font-black text-white">نشر الإجابة</button></FeedCard>
 <FeedCard title="مرّوا من هنا" subtitle={`${count} زيارة لملفك`} icon="👀"><div className="flex -space-x-2 space-x-reverse">{visitors.slice(0,6).map((x:any)=><div key={x.view_id} className="grid h-12 w-12 place-items-center overflow-hidden rounded-full border-3 border-white bg-[#EDF3F9]">{x.identity_revealed&&x.avatar_url?<img src={x.avatar_url} alt="" className="h-full w-full object-cover"/>:<UserRound size={20}/>}</div>)}</div><p className="mt-3 text-xs font-bold text-[#748198]">افتح هويات الزوار لمدة 24 ساعة من إعداداتك الاجتماعية.</p></FeedCard>
 <FeedCard title="مهمات اليوم" subtitle="اجمع نجومًا من نشاطك داخل لمتنا" icon="🎁"><div className="space-y-2">{missions.map((m:any)=><div key={m.code} className="flex items-center justify-between rounded-[18px] bg-[#F4F8FC] p-3"><div><p className="text-sm font-black">{m.title_ar}</p><p className="text-[11px] font-bold text-[#77839A]">{m.description_ar}</p></div><button disabled={busy||m.claimed} onClick={()=>claim(m.code)} className={`rounded-full px-3 py-2 text-xs font-black ${m.claimed?'bg-[#E8EEF4] text-[#8290A4]':'bg-[#FFF4C6] text-[#8C6200]'}`}>{m.claimed?'تم':'+'+m.reward_stars+' ⭐'}</button></div>)}</div></FeedCard>
 <FeedCard title="متواجد الآن" subtitle="حالة اجتماعية مؤقتة لمدة 24 ساعة" icon="💬"><input value={status} onChange={e=>setStatus(e.target.value)} className="h-12 w-full rounded-[18px] bg-[#F3F7FB] px-3 outline-none" placeholder="مثال: فاضي لكوباية قهوة وكلام"/><button onClick={social} disabled={busy||!status.trim()} className="lammetna-gradient mt-3 rounded-2xl px-4 py-2 text-sm font-black text-white">نشر الحالة</button></FeedCard>
 </main></AppShell>
}
function FeedCard({title,subtitle,icon,children}:{title:string;subtitle:string;icon:string;children:React.ReactNode}){return <section className="mobile-card mt-4 rounded-[26px] p-4"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-gradient-to-br from-[#E8F7FF] to-[#F4E8FF] text-xl">{icon}</div><div><p className="font-black">{title}</p><p className="text-xs font-bold text-[#77839A]">{subtitle}</p></div></div><span className="text-xl text-[#7E8AA0]">•••</span></div><div className="mt-4">{children}</div><div className="mt-4 flex items-center justify-end gap-5 text-[#45536C]"><span className="flex items-center gap-1 text-xs font-black"><Heart size={19}/>42</span><span className="flex items-center gap-1 text-xs font-black"><MessageCircle size={19}/>8</span><Share2 size={19}/></div></section>}
