'use client'
import {useEffect,useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {Bell,Plus,Users,Mic2,Lock,Globe2,Flame,Crown,Zap,Headphones,ChevronLeft,Pin} from 'lucide-react'
import {createClient} from '@/lib/supabase/client'
import {AppShell} from '@/components/app-shell'
import {BrandLogo} from '@/components/brand-logo'
type Space={id:string;owner_id:string;name:string;description:string|null;emoji:string|null;category:string|null;is_public:boolean;pinned_until:string|null;created_at:string;space_members:{count:number}[]}
export default function Spaces(){
 const s=useMemo(()=>createClient(),[]),r=useRouter(),[items,setItems]=useState<Space[]>([]),[uid,setUid]=useState(''),[show,setShow]=useState(false),[name,setName]=useState(''),[desc,setDesc]=useState(''),[emoji,setEmoji]=useState('🎙️'),[category,setCategory]=useState('عام'),[isPublic,setIsPublic]=useState(true),[password,setPassword]=useState(''),[joinPw,setJoinPw]=useState<Record<string,string>>({}),[notice,setNotice]=useState(''),[seats,setSeats]=useState<any[]>([]),[spot,setSpot]=useState<any>(null),[profiles,setProfiles]=useState<Record<string,any>>({})
 async function load(){const {data:{user}}=await s.auth.getUser();setUid(user?.id||'');const {data}=await s.from('spaces').select('id,owner_id,name,description,emoji,category,is_public,pinned_until,created_at,space_members(count)').limit(100);const sorted=((data||[]) as any).sort((a:Space,b:Space)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());setItems(sorted);if(sorted[0]){const [{data:sr},{data:sp}]=await Promise.all([s.from('space_seats').select('seat_no,user_id,seat_type').eq('space_id',sorted[0].id),s.from('space_pair_spotlights').select('user_a,user_b,status').eq('space_id',sorted[0].id).eq('status','active').maybeSingle()]);setSeats(sr||[]);setSpot(sp||null);const ids=[...(sr||[]).map((x:any)=>x.user_id),sp?.user_a,sp?.user_b].filter(Boolean);if(ids.length){const {data:ps}=await s.from('profiles').select('id,display_name,avatar_url').in('id',[...new Set(ids)]);setProfiles(Object.fromEntries((ps||[]).map((x:any)=>[x.id,x])))}}}
 useEffect(()=>{load()},[])
 async function create(){if(!name.trim())return;if(!isPublic&&password.trim().length<4){setNotice('كلمة مرور اللَمّة الخاصة لازم تكون 4 أحرف على الأقل.');return}const {data,error}=await s.rpc('create_lamma',{p_name:name.trim(),p_description:desc||null,p_emoji:emoji,p_category:category,p_is_public:isPublic,p_password:isPublic?null:password.trim()});if(error){setNotice('تعذر إنشاء اللَمّة.');return}setShow(false);if(data)r.push(`/spaces/${data}`)}
 async function join(x:Space){const {error}=await s.rpc('join_lamma',{p_space:x.id,p_password:x.is_public?null:joinPw[x.id]||null});if(error){setNotice(error.message.includes('wrong_password')?'كلمة المرور غير صحيحة.':'تعذر دخول اللَمّة.');return}r.push(`/spaces/${x.id}`)}
 const featured=items[0],star=seats.find(x=>x.seat_type==='star'||x.seat_no===1),a=spot?.user_a?profiles[spot.user_a]:null,b=spot?.user_b?profiles[spot.user_b]:null
 return <AppShell><main className="px-4 pb-5 pt-4"><header className="safe-top flex items-center justify-between"><div className="flex items-center gap-2"><BrandLogo size={48}/><div><h1 className="text-[31px] font-black">اللَمّة</h1><p className="text-[12px] font-bold text-[#6D7890]">غرف صوتية مباشرة تجمعنا دائمًا</p></div></div><button onClick={()=>setShow(!show)} className="grid h-11 w-11 place-items-center rounded-full bg-white text-[#1468F5] shadow-sm ring-1 ring-[#E0EAF6]"><Plus/></button></header>
 {notice?<p className="mt-3 rounded-2xl bg-[#EDF5FF] p-3 text-sm font-bold text-[#244E87]">{notice}</p>:null}
 {featured?<section className="lammetna-gradient hero-shadow mt-4 overflow-hidden rounded-[30px] p-5 text-white"><div className="flex items-center justify-between"><span className="rounded-full bg-white/20 px-3 py-1 text-xs font-black">⭐ اللَمّة الجديدة</span><span className="rounded-full bg-[#FF1975] px-3 py-1 text-xs font-black">مباشر 🎙️</span></div><div className="mt-4 grid grid-cols-[1fr_150px] gap-3"><div><h2 className="text-[31px] font-black">{featured.emoji||'☕'} {featured.name}</h2><p className="mt-1 text-sm font-bold leading-6 text-white/90">{featured.description||'سوالف يومية ومشاركة تجارب مع أصدقاء لمتنا'}</p><div className="mt-4 rounded-[22px] border border-white/25 bg-black/10 p-3"><p className="text-center text-sm font-black">⚔️ تحدي الآن</p><div className="mt-2 flex items-center justify-center gap-3"><Mini user={a} label="المقعد 2"/><span className="text-lg font-black">⚡ VS</span><Mini user={b} label="المقعد 3"/></div></div><button onClick={()=>join(featured)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-[20px] bg-white py-3 text-lg font-black text-[#6127DF]"><Headphones/>دخول الآن <ChevronLeft/></button></div><div className="flex flex-col items-center"><div className="relative h-32 w-32 overflow-hidden rounded-full border-4 border-[#FFD552] bg-white/15 shadow-[0_0_0_6px_rgba(255,210,70,.22)]">{star&&profiles[star.user_id]?.avatar_url?<img src={profiles[star.user_id].avatar_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full w-full place-items-center"><Users size={45}/></div>}<Crown className="absolute left-1/2 top-1 -translate-x-1/2 text-[#FFD02B]" fill="#FFD02B"/></div><span className="mt-2 rounded-full bg-[#FFE9A2] px-3 py-1 text-xs font-black text-[#7A4D00]">الضيف الملكي 👑</span><div className="mt-3 grid h-14 w-14 place-items-center rounded-full border-2 border-white bg-white/15"><Mic2 size={27}/></div><p className="mt-4 flex items-center gap-1 text-xs font-black"><Users size={15}/>+{featured.space_members?.[0]?.count||0} من الأعضاء</p></div></div></section>:null}
 <div className="mt-4 grid grid-cols-4 gap-2">{[[Flame,'الأكثر نشاطًا'],[Lock,'خاص'],[Users,'عام'],[Globe2,'كل اللَمّات']].map(([I,t]:any)=><button key={t} className="mobile-card rounded-[20px] p-3 text-[11px] font-black"><I className="mx-auto mb-1 text-[#1769F5]" size={21}/>{t}</button>)}</div>
 {show?<section className="mobile-card mt-4 rounded-[28px] p-4"><h3 className="text-lg font-black">إنشاء لَمّة جديدة</h3><div className="mt-3 grid grid-cols-[70px_1fr] gap-2"><input className="h-12 rounded-2xl bg-[#F2F6FB] px-3" value={emoji} onChange={e=>setEmoji(e.target.value.slice(0,4))}/><input className="h-12 rounded-2xl bg-[#F2F6FB] px-3" placeholder="اسم اللَمّة" value={name} onChange={e=>setName(e.target.value)}/></div><textarea className="mt-2 min-h-20 w-full rounded-2xl bg-[#F2F6FB] p-3" placeholder="وصف مختصر" value={desc} onChange={e=>setDesc(e.target.value)}/><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setIsPublic(true)} className={`rounded-2xl p-3 font-black ${isPublic?'lammetna-gradient text-white':'bg-[#EEF3F9]'}`}>🌍 عامة</button><button onClick={()=>setIsPublic(false)} className={`rounded-2xl p-3 font-black ${!isPublic?'lammetna-gradient text-white':'bg-[#EEF3F9]'}`}>🔒 خاصة</button></div>{!isPublic?<input type="password" className="mt-2 h-12 w-full rounded-2xl bg-[#F2F6FB] px-3" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/>:null}<button onClick={create} className="lammetna-gradient mt-3 h-12 w-full rounded-2xl font-black text-white">إنشاء اللَمّة</button></section>:null}
 <section className="mt-5"><h2 className="mb-3 text-xl font-black">اللَمّات النشطة الآن 🎙️</h2><div className="space-y-2">{items.map(x=><div key={x.id} className="mobile-card flex items-center gap-3 rounded-[22px] p-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-gradient-to-br from-[#E8F8FF] to-[#F4E8FF] text-2xl">{x.emoji||'🎙️'}</div><div className="min-w-0 flex-1"><p className="truncate font-black">{x.name}</p><p className="truncate text-xs font-bold text-[#738097]">{x.description||'لَمّة صوتية'}</p><div className="mt-1 flex gap-2 text-[10px] font-black"><span className={`rounded-full px-2 py-1 ${x.is_public?'bg-[#DFF8EE] text-[#11946A]':'bg-[#F1E4FF] text-[#8E31D8]'}`}>{x.is_public?'عام 🌐':'خاص 🔒'}</span><span className="text-[#748198]">{x.space_members?.[0]?.count||0} 👥</span></div>{!x.is_public?<input type="password" className="mt-2 h-9 w-full rounded-xl bg-[#F2F6FA] px-3 text-xs" placeholder="كلمة المرور" value={joinPw[x.id]||''} onChange={e=>setJoinPw(v=>({...v,[x.id]:e.target.value}))}/>:null}</div><button onClick={()=>join(x)} className="lammetna-gradient rounded-[18px] px-4 py-2 text-sm font-black text-white">دخول 🎧</button></div>)}</div></section>
 </main></AppShell>
}
function Mini({user,label}:{user:any;label:string}){return <div className="text-center"><div className="mx-auto h-12 w-12 overflow-hidden rounded-full border-2 border-white bg-white/15">{user?.avatar_url?<img src={user.avatar_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full w-full place-items-center"><Users size={19}/></div>}</div><p className="mt-1 rounded-full bg-white/13 px-2 py-1 text-[10px] font-black">{label}</p></div>}
